### PR TITLE
Use GitHub Actions to run the tests.

### PR DESCRIPTION
**Pull request by rmar3a**
- Travis changed their service so switching to use GitHub actions,
  which will hopefully be longer lasting than Travis.

### CODE REVIEW

**Comment by oschulte** [comment]
The checks are failing on this merge makes me nervous.

**Comment by rmar3a** [comment]
> The checks are failing on this merge makes me nervous.

Hi @oschulte , this pull request is not ready to be merged yet.  The issue is that the indices can not be created due to the length of the RChain names.

**Comment by rmar3a** [comment]
error

@oschulte I have managed to get the GitHub Actions to run the tests successfully; however, the non-deterministic values for the CP tables are happening again so it might take a few runs for the checks to pass.  From what I remember about the non-deterministic behaviour, it is due to how the precision is lost during the division operation in the database.  Retaining the full precision seemed to fix the issue, but then the UBC tool did not like it since the values were not adding up to 1.

I have attached an example of the non-deterministic values.  Basically the values 0.166667 and 0.166665 get swapped around.

**Comment by rmar3a** [comment]
@oschulte feel free to merge this pull request in if you want, but just be aware of the flaky runs if you do.  You can see the commit messages in this pull request for more information.

**Comment by rmar3a** [comment]
I thought about it more and one other possible reason for the difference might be the collation for the database where the columns are returned in a different order due to some names being upper case and others lower case.  Although, I am still not sure what is making all of this non-deterministic, the good thing is that the learned structure is still the same for either outcome.

**Comment by rmar3a** [comment]
@oschulte  I tried to lock the version of the Java JDK, but it looks like the results are still sometimes different per run.  I will need to look at the CP and BIF code when I have time.  Otherwise this pull request is okay to merge, but just be aware of the flaky runs if you do.

**Review by oschulte — APPROVED** [review]
looks great thank you!

**Pull request merged**
