### PR TITLE
Removing the src directory in the FactorBase/jar directory.

### PR DESCRIPTION
**Pull request by rmar3a**
- Removing all the scripts and the configuration file in
  FactorBase/jar/src to prevent code divergence and any confusion
  that may arise due to the duplication of files.
- As far as I can tell, FactorBase/src seems to contain the most
  up-to-date versions of these files.

### CODE REVIEW

**Comment by rmar3a** [comment]
It looks like the build expects these files (the files I deleted in this pull request) to be there.  I will work on adding a parameter to be able to specify the scripts directory and configuration file, which would fix this issue correctly.

**Comment by oschulte** [comment]
so we can't do this yet?

**Comment by rmar3a** [comment]
Oh wait, it looks like I mis-read the error message.  It's trying to find the configuration file, so once I put it back I think the rest might be fine.

**Comment by rmar3a** [comment]
This change is superceded by #77

**Pull request closed without merging**
