### PR TITLE
Moved the logic for CT table data extraction into a new class.

### PR DESCRIPTION
**Pull request by rmar3a**
- Moved the logic for extracting information from data in
  ContingencyTableGenerator.java to a new DataExtractor interface so
  that the data source passed to ContingencyTableGenerator can be
  changed more easily.
- Created a new DataSet class to help group data and associated
  metadata together.
- Created a new exception called DataExtractionException to help wrap
  exceptions that are thrown by different implementations of the
  DataExtractor interface.
- Updated the code and tests to use this new code.

### CODE REVIEW

**Comment by oschulte** [comment]
Nice step, this will make things easier for us and for other people.

**Comment by rmar3a** [comment]
Currently running FactorBase on 06 with this code for IMDB_MovieLens.  Hopefully it all goes well!

**Comment by rmar3a** [comment]
The runs have completed and the output looks the same except for possible differences due to smoothing (the graph is the same, but the values in the tables are slightly different).
It ran into about 120 minutes, whereas it used to run in about 100 minutes (prior to switching from Tetrad to our new CTGenerator code)

**Comment by oschulte** [comment]
can we delete a data extractor map after we've done with our learning? I.e. after we've got the BN for an rchain or a pvar?

**Pull request merged**
