### PR TITLE
Set the default collation to utf8_general_ci.

### PR DESCRIPTION
**Pull request by rmar3a**
- When moving to the new database server, collation errors appeared
  due to inconsistent collations between tables being joined so the
  default has been consistently set to utf8_general_ci.
- utf8_general_ci is less accurate when sorting, but has slightly
  better performance according to information online.

Here is a sample runtime breakdown for unielwin on 01:
```
Start Program...
Runtime[Logger + Config Initialization]: 26ms.
Runtime[Creating Database Connection]: 263ms.
Runtime[Creating Setup Database]: 1028ms.
Runtime[Creating Global Lattice]: 100ms.
Runtime[Creating CT Tables]: 407ms.
Runtime[Running BayesBaseH]: 7388ms.
Runtime[Cleanup Database]: 57ms.
Runtime[Total]: 9271ms.
Program Done!
```
And here is a breakdown for unielwin on the new database server (cs-ml-dev):
```
Start Program...
Runtime[Logger + Config Initialization]: 41ms.
Runtime[Creating Database Connection]: 267ms.
Runtime[Creating Setup Database]: 17054ms.
Runtime[Creating Global Lattice]: 721ms.
Runtime[Creating CT Tables]: 8025ms.
Runtime[Running BayesBaseH]: 40535ms.
Runtime[Cleanup Database]: 1860ms.
Runtime[Total]: 68505ms.
Program Done!
```
It is significantly slower!  Also, this change will prevent us from running on the 01 - 06 VMs.  Fortunately the changes are fairly small so reverting them shouldn't be a problem if we need to revert them :slightly_smiling_face: 

Note: This pull request updates the version of MariaDB for the Travis build to match the one used on the new database server and fixes the inconsistency that we were seeing for smoothing!

### CODE REVIEW

**Comment by rmar3a** [comment]
It looks like the build is running into the same error that the 01-06 VMs are running into :slightly_frowning_face:

**Comment by rmar3a** [comment]
It's very strange, the order of the values in the <TABLE> tag changed with each re-run of the build.  All I did was force a rebuild, so the code was the same for each build, but the results came out different...I will need to look into this otherwise it will just keep happening.

**Comment by rmar3a** [comment]
- The first build issue was that the key length was too long.  This was fixed by updating the Travis build to a newer version of MariaDB (10.3).
- The second build issue was the non-deterministic behaviour that we've been getting for the smoothing.  This was fixed by increasing the precision on the Java and MySQL sides.

**Comment by oschulte** [comment]
the issue is expanding the precision

**Pull request merged**
