### PR TITLE
Revert "command out cp GENERATION"

### PR DESCRIPTION
**Pull request by rmar3a**
This reverts commit c01d7febb741ea400e76e3687b63bb5576381237.

Reverting the commit so that CP tables are generated again.

### CODE REVIEW

**Comment by rmar3a** [comment]
@oschulte actually I did use the lattice mapping to figure out the mapping between the orig_rnids and short_rnids.  What is the correct way to find this mapping?  Or is your concern more about code cohesion?

**Comment by oschulte** [comment]
1. Lattice_RNodes still has orig_rnid, argh! I feel like we're missing my latest version of the lattice stuff. Good news though: CT and BN tables are looking good.

2. Ternary Relations should be in unielwin_setup only.

**Comment by rmar3a** [comment]
@oschulte for the first point it looks like we might have your latest code?  I found this commit:
https://github.com/sfu-cl-lab/FactorBase/commit/52ba39f2c27e5998d574b155726a3c85acc0753a

For the second point I've created another pull request here:
#64

**Comment by rmar3a** [comment]
This pull request is obsolete.  The successor to it is #65 so closing this pull request and deleting the branch.

**Pull request closed without merging**
