### PR TITLE
Remove early indices

### PR DESCRIPTION
**Pull request by rmar3a**
We were creating indices before inserting data into the output table for sort merge, which was slowing the performance down a little bit, so this logic has been removed.  This change also fixes the duplicated indices we were seeing in the false tables.  Here is an example of duplicated indices:
```
BEFORE CHANGES:
mysql> show index from `a_star`;
+--------+------------+----------+--------------+------------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table  | Non_unique | Key_name | Seq_in_index | Column_name            | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+--------+------------+----------+--------------+------------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| a_star |          1 | a_star   |            1 | MULT                   | A         |          21 |     NULL | NULL   |      | BTREE      |         |               |
| a_star |          1 | a_star   |            2 | intelligence(student0) | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
| a_star |          1 | a_star   |            3 | popularity(prof0)      | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
| a_star |          1 | a_star   |            4 | ranking(student0)      | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
| a_star |          1 | a_star   |            5 | teachingability(prof0) | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
+--------+------------+----------+--------------+------------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
5 rows in set (0.00 sec)

mysql> show index from `a_false`;
+---------+------------+----------+--------------+------------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table   | Non_unique | Key_name | Seq_in_index | Column_name            | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+---------+------------+----------+--------------+------------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| a_false |          1 | a_star   |            1 | MULT                   | A         |          21 |     NULL | NULL   |      | BTREE      |         |               |
| a_false |          1 | a_star   |            2 | intelligence(student0) | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
| a_false |          1 | a_star   |            3 | popularity(prof0)      | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
| a_false |          1 | a_star   |            4 | ranking(student0)      | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
| a_false |          1 | a_star   |            5 | teachingability(prof0) | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
| a_false |          1 | a_false  |            1 | MULT                   | A         |          21 |     NULL | NULL   |      | BTREE      |         |               |
| a_false |          1 | a_false  |            2 | intelligence(student0) | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
| a_false |          1 | a_false  |            3 | popularity(prof0)      | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
| a_false |          1 | a_false  |            4 | ranking(student0)      | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
| a_false |          1 | a_false  |            5 | teachingability(prof0) | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
+---------+------------+----------+--------------+------------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
10 rows in set (0.00 sec)

AFTER CHANGES:
mysql> show index from `a_star`;
+--------+------------+----------+--------------+------------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table  | Non_unique | Key_name | Seq_in_index | Column_name            | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+--------+------------+----------+--------------+------------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| a_star |          1 | a_star   |            1 | MULT                   | A         |          21 |     NULL | NULL   |      | BTREE      |         |               |
| a_star |          1 | a_star   |            2 | intelligence(student0) | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
| a_star |          1 | a_star   |            3 | popularity(prof0)      | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
| a_star |          1 | a_star   |            4 | ranking(student0)      | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
| a_star |          1 | a_star   |            5 | teachingability(prof0) | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
+--------+------------+----------+--------------+------------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
5 rows in set (0.00 sec)

mysql> show index from `a_false`;
+---------+------------+----------+--------------+------------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table   | Non_unique | Key_name | Seq_in_index | Column_name            | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+---------+------------+----------+--------------+------------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| a_false |          1 | a_false  |            1 | MULT                   | A         |          21 |     NULL | NULL   |      | BTREE      |         |               |
| a_false |          1 | a_false  |            2 | intelligence(student0) | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
| a_false |          1 | a_false  |            3 | popularity(prof0)      | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
| a_false |          1 | a_false  |            4 | ranking(student0)      | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
| a_false |          1 | a_false  |            5 | teachingability(prof0) | A         |          21 |     NULL | NULL   | YES  | BTREE      |         |               |
+---------+------------+----------+--------------+------------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
5 rows in set (0.01 sec)
```

### CODE REVIEW

**Comment by oschulte** [comment]
good catch. Does it help with runtime as well?

**Comment by rmar3a** [comment]
Yes, I posted the runtimes on Slack.  Before the index change Financial took about 67 minutes and after the index change it took about 45 minutes.  As for IMDB MovieLens the runtime for two trials were:
```
real    241m4.809s
real    247m0.220s
```
which I believe is a little bit faster than before, but not as much of an improvement as Financial.

**Comment by oschulte** [comment]
funny I didn't see the runtimes. Still it's going in the right direction. !

**Comment by rmar3a** [comment]
Just some follow-up run times I've collected.

Before this change (having the indices before insertion) gives run times like:
```
real    286m2.421s
```
and after the change (removing the indices before insertion) gives run times like:
```
real    253m11.921s
```
So this is a decrease in the runtime for IMDB MovieLens, but not in the same percentage as Financial.

**Comment by rmar3a** [comment]
More run time information can be found at pull request https://github.com/sfu-cl-lab/FactorBase/pull/108

**Pull request merged**
